on:
  pull_request:
    branches: [main, next]
    paths:
      - 'proofs/**'

jobs:
  # Enforces the update of a changelog file on every pull request
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: dangoslen/changelog-enforcer@8b5e9dc3121363bb7c0115f8533404d92af382de
        with:
          changeLogPath: proofs/CHANGELOG.md